# Generated by Django 4.1.1 on 2022-10-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeatherMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Izena')),
                ('owm', models.CharField(blank=True, max_length=200, null=True, verbose_name='code')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='webpath')),
                ('euskalmet', models.CharField(blank=True, max_length=200, null=True, verbose_name='euskalmet icon')),
                ('euskalmet_new', models.CharField(blank=True, max_length=200, null=True, verbose_name='euskalmet icon new')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Icon')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sortze data')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edizio data')),
            ],
            options={
                'verbose_name': 'OpenWeatherMap',
                'verbose_name_plural': 'OpenWeatherMap',
                'ordering': ['created'],
            },
        ),
    ]
