# Generated by Django 4.1.1 on 2022-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_openweathermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikespot',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
