# Generated by Django 4.1.1 on 2022-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gpstracks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpstracks',
            options={'ordering': ['created'], 'verbose_name': 'GpsTrack', 'verbose_name_plural': 'GpsTracks'},
        ),
        migrations.AddField(
            model_name='warmshower',
            name='done',
            field=models.BooleanField(blank=True, null=True, verbose_name='gpx'),
        ),
    ]
