# Generated by Django 4.1.1 on 2022-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='end_flag',
            field=models.ImageField(blank=True, null=True, upload_to='img/icon'),
        ),
        migrations.AddField(
            model_name='icon',
            name='start_flag',
            field=models.ImageField(blank=True, null=True, upload_to='img/icon'),
        ),
    ]
