# Generated by Django 4.1.1 on 2022-10-07 18:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_icon_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='img/pointsInterest')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='img/pointsInterest')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='img/pointsInterest')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='img/pointsInterest')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interesting point',
                'verbose_name_plural': 'Points of interest',
                'ordering': ['created'],
            },
        ),
    ]
