# Generated by Django 4.1.1 on 2022-10-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pointsinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsinterest',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
