# Generated by Django 4.1.1 on 2022-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_gpx_gpstracks_gpx_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpstracks',
            name='auto_gpx',
            field=models.BooleanField(blank=True, null=True, verbose_name='auto_gpx'),
        ),
        migrations.AddField(
            model_name='gpstracks',
            name='gpx',
            field=models.BooleanField(blank=True, null=True, verbose_name='gpx'),
        ),
        migrations.AlterField(
            model_name='gpstracks',
            name='gpx_path',
            field=models.FileField(upload_to='gpx_path'),
        ),
    ]
