# Generated by Django 4.1.5 on 2023-02-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gpstracks_auto_gpx_gpstracks_gpx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsTrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='fechahora')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('track_data', models.JSONField(blank=True, null=True, verbose_name='Tracking data')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GpsTrackingData',
                'verbose_name_plural': 'GpsTrackingData',
                'ordering': ['created'],
            },
        ),
    ]
